# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows-x64:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install qt static
        uses: orestonce/install-qt@main
        with:
          version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
      - name: build
        run: |
          cd voice2srt && qmake && mingw32-make release && cd ..
          dir voice2srt\release\voice2srt.exe
      - name: pack
        run: |
          mkdir voice2srt_windows_x64-${{ github.ref_name }} && cd voice2srt_windows_x64-${{ github.ref_name }}
          copy ..\voice2srt\release\voice2srt.exe .\
          Invoke-WebRequest -URI "https://github.com/orestonce/voice2srt/releases/download/v0.1/resource.7z" -OutFile resource.7z
          7z x resource.7z
          del resource.7z
          cd ..
          dir voice2srt_windows_x64-${{ github.ref_name }}
          7z a voice2srt_windows_x64-${{ github.ref_name }}.7z voice2srt_windows_x64-${{ github.ref_name }}